### PR TITLE
Make code following PEP8 standards

### PR DESCRIPTION
**Pull request by mtrellet**
- Ignore E501 for readability

### CODE REVIEW

**Comment by mtrellet** [comment]
run jenkins

**Comment by mtrellet** [comment]
run jenkins

**Comment by mtrellet** [comment]
run jenkins

**Comment by mtrellet** [comment]
run jenkins

**Comment by mtrellet** [comment]
run jenkins

**Comment by mtrellet** [comment]
run jenkins

**Comment by mtrellet** [comment]
run jenkins

**Comment by mtrellet** [comment]
run jenkins

**Comment by mtrellet** [comment]
Test

**Comment by mtrellet** [comment]
run jenkins

**Comment by orviz** [comment]
retest this please

**Pull request closed without merging**
